### ISSUE TITLE
Organization Dashboard (Member Manager View)

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-api#1]
**Summary**

Develop the backend service to support the LFX EasyCLA Organization Dashboard (Member Manager View).

**Background**

The LFX EasyCLA Organization Dashboard front-end, request/response models are documented in the [EasyCLA v2 PRD](https://confluence.linuxfoundation.org/display/PROD/EasyCLA+v2+PRD#EasyCLAv2PRD-OrganizationDashboard(MemberManagerView).  Enhance the existing API to incorporate the referenced path/endpoint.

**User Story**

As an LFX Community Bridge EasyCLA Organization Manager, I can view the list of Foundations affiliated with my Organization.

**Tasks**
- [x] Create a `orgs` package in the main folder
- [x] Define the Swagger API specification for the GET easycla-api.lfcla.com/v4/orgs/{salesForceOrganizationId} endpoint (see `swagger/cla.yml`)
- [x] Provide a handler in the new `orgs` package to map the API spec to a specific handler function. For examples, see EasyCLA v1 go backend or Organization Service
- [x] Add the handler to the server.go setup/configuration
- [x] Create a service implementation - define the interface and implementation
- [x] Create a mock repository implementation - define the interface and return sample data outlined in the PRD write-up. We will create an in-memory database and real RDS repository implementation later.
- [x] Connect the server to the handler to the service to the mock repository.
- [x] Test the service implementation locally via cURL, PostMan or similar.  Results should closely match PRD examples.
- [x] Follow the Fork/Clone/Branch/Commit/PR model to submit these changes
 
**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running locally.

**References**

- EasyCLA v2 PRD: https://confluence.linuxfoundation.org/display/PROD/EasyCLA+v2+PRD
