### ISSUE TITLE
CLA Group Management

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-api#12]
## Summary

This task is to create an API for CLA Group Management

## Background

A CLA Group is a logical organization under a single Foundation (also often called a Project) that groups a collection of related source code organizations (e.g. GitHub Organization or Gerrit Group) and/or repositories under a single CLA legal grouping/policy.

The CLA Group consists of:
1. CLA Group Name
1. A reference to the parent Foundation/Project (this will be a SFID)
1. A pair of CLA templates (CCLA and ICLA)
1. Flags to indicate which CLA templates are active/enabled for this CLA Group
1. A collection of one or more Project Managers (references to user objects)
1. References to the source code organizations/repositories

This task will define, implement, validate and test the API services supporting creating, updating, viewing, searching and deleting CLA Groups.

## Tasks

1. [x] Define a swagger specification for *creating* a CLA group
   1. The swagger specification will accept the foundation id (SFID), CLA Group Name, one or more Project managers (SFID's of users)
1. [x] Define a swagger specification for *updating* a CLA group
1. [x] Define a swagger specification for *deleting* a CLA group
1. [x] Define a swagger specification for *searching* or *listing* a list of CLA groups by foundation id. Include pagination params as well: page_size/limit, offset, order_by as the list of CLA groups should be managed.
1. [x] Define a swagger specification for *searching* or *listing* a list of CLA groups by a project manager id. Include pagination params as well: page_size/limit, offset, order_by as the list of CLA groups should be managed.
1. [x] Define the CLA group database schema using `dbmate`. Fields might include:
   1. id: pk GUID type v4 or something similar
   1. CLA Group Name
   1. Parent foundation id
   1. date created
   1. date updates/last updated
   1. ccla enabled flag (boolean)
   1. icla enabled flag (boolean)
   1. CCLA and ICLA template definitions will be defined in another table
1. [x] Create a repo implementation for the CRUD operations defined above
1. [x] Create a service layer to support the REST operations defined above
1. [x] Create an API handler to bin the Swagger specification to the implementation
1. [x] Add the handler/service/repo to the setup to stitch it together
1. [x] Create an audit event in the audit table when a CLA Group is added, updated or deleted (we will backfill the API user info later)
1. [x] test/validate CRUD operations

This is the first piece of several to establish the Project/CLA Group/Template setup required for on-boarding a project.

## User Story

1. As an LF admin, I want to create, update and delete CLA groups under a Foundation to support project setup and maintenance.
1. As a Project Manager, I want to view my CLA groups under a given Foundation.

## Acceptance Criteria

- [x] Unit tests for create/delete audit events
- [ ] Create function tests for audit events (see @dealako for CI/CD automation)
- [ ] Demonstration of audit service to product owners.

## References

See existing `cla-project-{STAGE}` table concepts/schema already defined in DynamoDB for an example.
