### ISSUE TITLE
API Gateway Authentication

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-api#13]
## Summary

We want to leverage the API Gateway Authentication headers to apply role-based access to the Easy CLA services.

## Background

The EasyCLA v2 system will reside behind the LF platform API Gateway. The REST services we develop will be protected by the Gateway and the ACS service.  We need to leverage this by restricting access based on user roles.

## Tasks

- [x]  update the swagger specification to include authentication (see org service or project service as an example)
- [x] include the LFX Kit library, [see the org service example](https://github.com/LF-Engineering/organization-service/blob/master/Gopkg.toml#L49-L51)
- [x] Omit the security protection for api-docs and the health and status
- [x] Auth user object will be included in the API requests
- [x] Bind the API security to the LFX auth model in the server configuration
- [x] Rebuild and ensure the authUser as part of the API request (like request params)
   as a function parameter
- [x] Ensure that only LF Admins can create CLA Groups as defined in issue #12
- [ ] Note: you will need to obtain an Authorization Bearer Token for API calls. We have two approaches for this:
      - Open and log into the LXF UI, from the console: https://lfx.dev.platform.linuxfoundation.org/home/dashboard

Example 1:

1. LF Admin logs in
1. Makes an API request to see the audit log
1. Code reviews the roles/access for the user, see that user is the LF Admin role
1. API allows all audit logs in the response

Example 2:

1. A company manager for Google logs in
1. Makes an API request to see the audit log
1. The code reviews the roles/access for the user, see that user is the company
   manager
1. we look up the user’s company id
1. pass the company ID to the backend to filter the audit log based on the company id

## Acceptance Criteria

Demonstrate to the stakeholders.

## References

See the LF Core Platform organization or the project service as an example.
