### ISSUE TITLE
CLA Templates Service

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-api#31]
## Summary

Create a new templates table and support service for the EasyCLA system.

## Background

The EasyCLA system requires a standard template for Project Managers to select from in order to establish legal documents for their project CLA.  This issue will provide a database table and API services to support creating, searching, updating and deleting the templates.

## User Story

- As a Project Manager, I want to select the Apache Style CLA template for my project.
- As an LF Admin, I want to create a new CLA template for projects to use.
- As an LF Admin, I want to update an existing CLA template for projects to use.
- As an LF Admin, I want to delete an existing CLA template.

## Tasks

- [x] Develop a database schema to hold CLA templates.  Columns should include a unique id/pk, date created, date modified, template name, template description, template version, a text blob to hold the template text encoded as an HTML fragment (see: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/template/repository.go#L546), and a JSON blob to hold the template meta-data (see: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/template/repository.go#L412)
- [x] Develop and implement the Swagger specification to allow CRUD operations
- [x] Develop and implement the repository/DB API to allow CRUD operations
- [x] Develop and implement the service layer to support the API
- [x] Develop and implement the request/response handler - connect the logic through the API
- [x] Add the security layer - only users with the LF Admin role can create/update/delete. All users with the project manager role assigned can read for now.

## Acceptance Criteria

- Demonstrate the working API in the DEV environment.

## References

- [EasyCLA v1 templates](https://github.com/communitybridge/easycla/tree/master/cla-backend-go/template)
