### ISSUE TITLE
Audit Service Table

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-api#8]
**Summary**

Create an Audit Service for recording events in the EasyCLA system.

**Background**

Since the EasyCLA system processes permissions relating to legal CLA documents, a comprehensive audit log needs to record all access and permission events.  Examples include add permission, delete permission, create a signature, delete a signature, add/update/delete whitelist entry.

**Task**

- [x] Review the `dbmate` documentation
- [x] Use `dbmate new create_audit_table` to construct a SQL script to provision and migrate the audit table definition.  Include this in the PR.

Suggested columns (will refine):
- in the `-- migrate:up` define a database table schema.
- id: pk GUID type v4 or something similar
- event: string (we will have a set of enum values)
- user: string (id of the user/person who created the event - e.g. logged in user)
- project id: string (id of the SFID project)
- company id: string (id of the organization/company)
- event date time (date-time of the event)
- event_data: blob, contain event details, such as: `{"github_whitelist": ["prasannamahajan", "ddeal"]}`

Also:

- [x] create a Swagger specification for `SearchEvent `, should include search by event type, by the user, project id, company/org, and by a time window. Support any combination of these parameters.  Also, include pagination params as well: page_size/limit, offset, order_by as the list of events may/will be large.
- [x] create a repo implementation for `SearchEvent`
- [x] create a service layer for `SearchEvent`
- [x] add the handler/service/repo to the setup/glue it together for `SearchEvent`.
- [x] create a repo implementation for `CreateEvent`
- [x] create a service layer for `CreateEvent` - note: this service will NOT have a public endpoint or definition in swagger.
- [x] test/validate creating and retrieving audit values

We’ll use this for auditing everything in the backend/events, etc.

**Acceptance Criteria**

- [ ] Unit tests for create/delete audit events
- [ ] Create function tests for audit events (see @dealako for CI/CD automation)
- [ ] Demonstration of audit service to product owners

**References**

We have similar examples of a Search Endpoint used in the Platform Core Services, such as the Organization Service: https://github.com/LF-Engineering/organization-service/blob/master/swagger/organization-service.yaml#L61 (private repo).
